name: Update Website

on:
  push:
    branches:
    - develop

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Website Content
      run: |
        bundler install
        bundler exec jekyll build
    
    - uses: actions/upload-artifact@v1
      with:
        name: www
        path: _site
    
    - name: Copy over before commit
      run: |
        cp -rf _site/* ./
        rm -rf _*
        rm *.md
        rm Gemfile Gemfile.lock Dockerfile
        git stash
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        git checkout --orphan master
        git stash pop
        git add .
        git commit -m "Updating build branch"
        git push --set-upstream origin master